# Configurações do Servidor
server.port=8080

# Configurações de E-mail (SMTP)
# Substitua pelos dados do seu provedor (ex: Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=SEU_EMAIL@gmail.com
spring.mail.password=SUA_SENHA_DE_APP
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Desabilitar segurança para testes locais simples
spring.main.allow-bean-definition-overriding=true
